import '../styles/modern-normalize.css';
import '../styles/style.css';
import '../styles/header.css';
import '../styles/hero.css';
import '../styles/about.css';
import '../styles/featured.css';
import '../styles/contact.css';
import '../styles/footer.css';
import '../styles/util.css';